name: 'Substring branch name after a separator'
description: 'Substring the branch name (that trigger the action) after the first occurrence of a given separator.'
icon: 'box'
color: 'gray-dark'
inputs:
  separator:
    description: 'Separator'
    required: true
    default: ''
outputs:
  substring:
    description: 'The branch name substring.'
runs:
  using: 'node12'
  main: 'dist/index.js'